version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres
      postgres_user: postgres
      postgres_db: nlw
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"